matrix:
  include:
    - language: go
      os:
        - linux
      dist:
        - bionic
      go:
        - 1.15.x
      script:
        - go build main.go
    - language: node_js
      sudo: required
      node_js:
        - '12'
      before_install:
        - npm install -g npm@latest
        - npm install -g ganache-cli truffle
      install:
        - npm install
      script:
        - ganache-cli &
        - cd contract/ && truffle test
